### ISSUE TITLE
Neovim Config

### ISSUE THREAD

**Issue by dominikb1888** [malob/nix-config#18]
Thanks for sharing your config here! I used it with minor changes and it is a really neat set of tools and customizations.

I had two errors on the neovim config the past weeks and fixed them now. 

1. init_lsp_saga is deprecated it should be `require'lspsaga'.setup {` now apparently
2. indent_blankline had similar changes to the api and the new line would be: `require'ibl'.setup {`

Happy to send a PR if this is an error others have two and the change make sense for me it removes two error messages on neovim startup.

**Comment by malob** [comment]
Thanks. I've just pushed a commit to fix `indent-backline.nvim`.

As for `lspsaga`, I'm currently in the process of moving away from it. I'll probably push the changes in the next couple of weeks.
